### PR TITLE
linux and macos binary updated to v2.2.0

### LINKED ISSUE #18: Update binaries
New version of the library is released. Can you please update the binaries?

https://github.com/danielgtaylor/jpeg-archive/releases

### PR DESCRIPTION
**Pull request by adityapatadia**
This closes #18

### CODE REVIEW

**Comment by adityapatadia** [comment]
@1000ch can you merge this?

**Comment by sindresorhus** [comment]
@adityapatadia Sorry, we don't accept binary submissions from random people as we can't trust those binaries. One of the maintainers will need to update the binaries. You also incorrectly changed the permission of one of the binaries.

**Comment by adityapatadia** [comment]
Okay. It would be great if someone can update the binaries. It takes just few minutes to compile but will give users improved binaries. Current ones date back to 2015.

**Comment by adityapatadia** [comment]
I had this thought. Is it possible I can build binary in say some docker container or say travis CI kind of system and submit along with its MD5 hash so that it's guaranteed to be authentic?

**Comment by adityapatadia** [comment]
@sindresorhus what do you think is best way to update the binaries? I need to get them updated.

**Comment by kevva** [comment]
@adityapatadia, I will update them. I'm looking into a solution so that users can fall back to existing binaries on their system.

**Comment by adityapatadia** [comment]
Is there a specific reason to keep those 4 year old binaries?

May be we can just tag new version and write in readme to use older version for those binaries.

**Comment by kevva** [comment]
There's no particular reason. I just haven't been as active to keep them updated.

**Pull request closed without merging**
